name: weather_forecast
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_screenutil: 5.9.0
  get: 4.6.6
  connectivity: 3.0.6
  geolocator: 11.0.0
  http: 1.2.1
  fluttertoast: 8.2.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

